import localFont from "next/font/local";
import "./globals.css";
import { getServerSession } from "next-auth";
import AuthProvider from "@/utils/sessionProvider";
import ReactToast from "@/components/react-toast";
import { Poppins } from '@next/font/google';
import { DM_Sans } from '@next/font/google';
import { Beau_Rivage } from '@next/font/google';
import NextTopLoader from "nextjs-toploader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  weight: ['400', '500', '700'], // Include desired weights
  subsets: ['latin'],           // Specify subsets
});

const dmSans = DM_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

const beauRivage = Beau_Rivage({
  weight: '400', // Beau Rivage only has 400 weight
  subsets: ['latin'], // Adjust subsets as needed
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession() || null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} ${dmSans.className} ${beauRivage.className} antialiased`}
      >
        <AuthProvider session={session}>
          <NextTopLoader />
            {children}
          <ReactToast />
        </AuthProvider>
      </body>
    </html>
  );
}
